# Importing the libraries

In [11]:
import pandas as pd
import numpy as np

# Importing & Splitting Data

## Importing the dataset

In [2]:
# dataset = pd.read_csv('ENTER_THE_NAME_OF_YOUR_DATASET_HERE.csv')
dataset = pd.read_csv('data/data_regression.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

## Splitting the dataset into the Training set and Test set

In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

# Linear Regression

In [4]:
import statsmodels.api as sm

In [5]:
X_const = sm.add_constant(X) # adding a constant
model = sm.OLS(y, X).fit()
print(model.summary())

                                 OLS Regression Results                                
Dep. Variable:                      y   R-squared (uncentered):                   1.000
Model:                            OLS   Adj. R-squared (uncentered):              1.000
Method:                 Least Squares   F-statistic:                          1.939e+07
Date:                Sat, 26 Nov 2022   Prob (F-statistic):                        0.00
Time:                        20:09:13   Log-Likelihood:                         -29068.
No. Observations:                9568   AIC:                                  5.814e+04
Df Residuals:                    9564   BIC:                                  5.817e+04
Df Model:                           4                                                  
Covariance Type:            nonrobust                                                  
                 coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------

In [10]:
ypred = model.predict(X)
ypred[:5]

array([471.09692422, 447.54877425, 480.38530674, 449.65358675,
       469.40077104])

# Reviewing RMSE

In [12]:
from sklearn import metrics
import math

In [15]:

mse = metrics.mean_squared_error(y, ypred)
rmse = math.sqrt(mse)
rmse

5.048769168774747

In [16]:
rmse2 = np.exp(rmse)
rmse2

155.83054529955712

### Training the Multiple Linear Regression model on the Training set

In [17]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

### Predicting the Test set results

In [18]:
y_pred = regressor.predict(X_test)
#np.set_printoptions(precision=2)

In [20]:
y_pred[:5]

array([431.43458966, 458.57522935, 462.76604909, 448.60649816,
       457.87605198])

### Evaluating the Model Performance

In [21]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.9323789104734466

# Polynomial Regression

## Training the Polynomial Regression model on the Training set

In [22]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
poly_reg = PolynomialFeatures(degree = 4)
X_poly = poly_reg.fit_transform(X_train)
regressor = LinearRegression()
regressor.fit(X_poly, y_train)

LinearRegression()

## Predicting the Test set results

In [23]:
y_pred = regressor.predict(poly_reg.transform(X_test))
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[433.98 431.23]
 [457.97 460.01]
 [460.69 461.14]
 ...
 [470.31 468.9 ]
 [477.79 473.9 ]
 [440.03 437.07]]


## Evaluating the Model Performance

In [ ]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

# Decision Tree

## Training the Decision Tree Regression model on the Training set

In [25]:
from sklearn.tree import DecisionTreeRegressor
regressor = DecisionTreeRegressor(random_state = 0)
regressor.fit(X_train, y_train)

DecisionTreeRegressor(random_state=0)

## Predicting the Test set results

In [26]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[432.98 431.23]
 [454.67 460.01]
 [463.6  461.14]
 ...
 [475.89 468.9 ]
 [474.15 473.9 ]
 [439.99 437.07]]


## Evaluating the Model Performance

In [27]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.9229733351311707

# Random Forest

## Training the Random Forest Regression model on the whole dataset

In [28]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 10, random_state = 0)
regressor.fit(X_train, y_train)

RandomForestRegressor(n_estimators=10, random_state=0)

## Predicting the Test set results

In [29]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[434.54 431.23]
 [458.79 460.01]
 [462.62 461.14]
 ...
 [470.44 468.9 ]
 [475.13 473.9 ]
 [439.56 437.07]]


## Evaluating the Model Performance

In [30]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.960853142550123

# Support Vector Regression

## Feature Scaling

#### We must perform feature scaling for SVR. To perform feature scaling we have to reshape the data

In [34]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values
y = y.reshape(len(y),1)

In [35]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [36]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
sc_y = StandardScaler()
X_train = sc_X.fit_transform(X_train)
y_train = sc_y.fit_transform(y_train)

## Training the SVR model on the Training set

In [37]:
from sklearn.svm import SVR
regressor = SVR(kernel = 'rbf')
regressor.fit(X_train, y_train)

/Applications/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


SVR()

## Predicting the Test set results

In [38]:
y_pred = sc_y.inverse_transform(regressor.predict(sc_X.transform(X_test)))
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[434.05 431.23]
 [457.94 460.01]
 [461.03 461.14]
 ...
 [470.6  473.26]
 [439.42 438.  ]
 [460.92 463.28]]


## Evaluating the Model Performance

In [39]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.948078404998626